// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OriginFrameWork.EntityFrameWork;

#nullable disable

namespace OriginFrameWork.EntityFrameWork.Migrations
{
    [DbContext(typeof(OriginDbContext))]
    [Migration("20250304113459_init3")]
    partial class init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OriginFrameWork.EntityFrameWork.MainDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<string>("CanItBeTransferred")
                        .HasColumnType("longtext");

                    b.Property<int?>("DeptrootId")
                        .HasColumnType("int");

                    b.Property<double?>("DevicePrice")
                        .HasColumnType("double");

                    b.Property<string>("DeviceSource")
                        .HasColumnType("longtext");

                    b.Property<int?>("DeviceStatus")
                        .HasColumnType("int");

                    b.Property<string>("DeviceStatusName")
                        .HasColumnType("longtext");

                    b.Property<string>("DeviceType")
                        .HasColumnType("longtext");

                    b.Property<string>("InStockTime")
                        .HasColumnType("longtext");

                    b.Property<string>("InStockUser")
                        .HasColumnType("longtext");

                    b.Property<string>("InventoryClassification")
                        .HasColumnType("longtext");

                    b.Property<string>("IsAccidentParts")
                        .HasColumnType("longtext");

                    b.Property<string>("IsItIdleAndBacklogged")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialCategory")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialName")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialNo")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialParameters")
                        .HasColumnType("longtext");

                    b.Property<string>("Memo")
                        .HasColumnType("longtext");

                    b.Property<int?>("OldOrNew")
                        .HasColumnType("int");

                    b.Property<string>("SlotNo")
                        .HasColumnType("longtext");

                    b.Property<string>("SourceId")
                        .HasColumnType("longtext");

                    b.Property<string>("SpecsType")
                        .HasColumnType("longtext");

                    b.Property<string>("StockName")
                        .HasColumnType("longtext");

                    b.Property<string>("StockNo")
                        .HasColumnType("longtext");

                    b.Property<int?>("StockNumber")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalParameters")
                        .HasColumnType("longtext");

                    b.Property<double?>("TotalAmount")
                        .HasColumnType("double");

                    b.Property<string>("Unit")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MainDevice");
                });
#pragma warning restore 612, 618
        }
    }
}
